version: '3.8'

services:
  youtube-audio-extractor:
    build: 
      context: ./src
      dockerfile: Dockerfile
    container_name: youtube-audio-extractor
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./cookies.txt:/app/cookies.txt:ro
      - ./logs:/app/logs
      - /tmp:/tmp
    environment:
      - YOUTUBE_COOKIES_PATH=/app/cookies.txt
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - youtube-audio-extractor
    profiles:
      - proxy 